services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_api.test
    restart: unless-stopped
    ports:
      - "10003:3000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      NODE_ENV: production

  db:
    build:
      context: .
      dockerfile: Dockerfile_db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGUSER=${USER_LOGIN}
      - PGPASSWORD=${USER_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USER_LOGIN} -d exercise_tracker" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
