name: CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Install vitest globaly
        run: npm install -g vitest

      - name: Audit dependencies
        run: npm audit fix
    
      - name: Setup test .env file
        run: |
          echo "POSTGRES_PASSWORD=admin" >> .env
          echo "USER_LOGIN=test" >> .env
          echo "USER_PASSWORD=test" >> .env
          echo "DB_HOST=localhost" >> .env

      - name: Run hello test
        run: vitest --reporter=verbose hello.test.mjs

      - name: Run users tests
        run: vitest --reporter=verbose users.test.mjs